const state={teams:[],ownTeam:'',opponentTeam:'',ownPlayers:[],selectedOwn:[],opponentPlayers:[],selectedOpp:[],result:null,loadingPlayers:false,analysisLoading:false};
const app=document.querySelector('#app');

async function api(path){const r=await fetch(path);const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.message||d.error||'API error');return d;}
async function init(){try{const d=await api('/api/teams');state.teams=d.teams;state.ownTeam=state.teams[0]?.id||'';state.opponentTeam=state.teams.find(t=>t.id!==state.ownTeam)?.id||'';await loadTeamPlayers();render();}catch(e){app.innerHTML=`<section class="card"><h2>Fehler</h2><p>${e.message}</p></section>`;}}
async function loadTeamPlayers(){state.loadingPlayers=true;try{const [own,opp]=await Promise.all([api('/api/teams/players?team='+encodeURIComponent(state.ownTeam)),api('/api/teams/players?team='+encodeURIComponent(state.opponentTeam))]);state.ownPlayers=own.players;state.opponentPlayers=opp.players;state.selectedOwn=[];state.selectedOpp=[];state.result=null;}finally{state.loadingPlayers=false;}}
function render(){const own=state.ownPlayers,opp=state.opponentPlayers;app.innerHTML=`<section class="grid two"><div class="card"><h2>1. Match Setup</h2>${select('Eigene Mannschaft','ownTeam',state.teams)}${select('Gegner','opponentTeam',state.teams.filter(t=>t.id!==state.ownTeam))}<h3>Eigene Spieler <span class="selection-count">${state.selectedOwn.length}/4</span></h3><p class="muted">Wähle genau vier Spieler. Die Auswahl verwendet die XTTV-Spieler-ID, nicht nur den Namen.</p>${state.loadingPlayers?'<div class="empty">Spieler werden geladen …</div>':players(own,state.selectedOwn,'own')}<button class="primary" data-action="analyze" ${state.selectedOwn.length!==4||state.analysisLoading||state.loadingPlayers?'disabled':''}>${state.analysisLoading?'Berechnung läuft …':'Optimale Aufstellung berechnen'}</button></div><div class="card highlight"><h2>${state.selectedOpp.length===4?'2. Neuoptimierung':'2. Optimale Aufstellung'}</h2>${resultHtml()}</div></section><section class="card"><h2>3. Tatsächliche Gegner</h2><p class="muted">Wähle die vier tatsächlich angetretenen Gegner. Ihre Positionen bleiben geheim. Auch hier zählt die XTTV-Spieler-ID.</p><h3>Gegner <span class="selection-count">${state.selectedOpp.length}/4</span></h3>${state.loadingPlayers?'<div class="empty">Spieler werden geladen …</div>':players(opp,state.selectedOpp,'opp')}${state.selectedOpp.length===4?'<div class="success">Vier Gegner ausgewählt – Positionen bleiben verborgen. Klicke oben auf „Optimale Aufstellung berechnen“, um neu zu berechnen.</div>':'<div class="empty">'+state.selectedOpp.length+'/4 Gegner ausgewählt.</div>'}</section>`;bind();}
function select(label,field,items){return `<label>${label}<select data-field="${field}" ${state.loadingPlayers||state.analysisLoading?'disabled':''}>${items.map(x=>`<option value="${x.id}" ${state[field]===x.id?'selected':''}>${x.name}</option>`).join('')}</select></label>`;}
function players(list,selected,group){const duplicateNames=new Set(list.filter(p=>list.filter(x=>x.name===p.name).length>1).map(p=>p.name));return `<div class="players">${list.map(p=>`<button class="player ${selected.includes(p.id)?'selected':''}" data-player="${p.id}" data-group="${group}" ${state.analysisLoading?'disabled':''}><span><strong>${p.name}</strong>${duplicateNames.has(p.name)?`<small class="player-id">XTTV-ID ${p.id}</small>`:''}</span><small>${p.games} Einzel · ${pct(p.win_rate)} Siege</small></button>`).join('')}</div>`;}
function resultHtml(){if(state.analysisLoading)return '<div class="analysis-loading" role="status" aria-live="polite"><div class="loading-title">Berechnung läuft</div><div class="loading-track"><div class="loading-bar"></div></div><div class="loading-text">Einmaliger Datenbankabruf. Danach wird die komplette Analyse ausschließlich im Speicher berechnet.</div><div class="loading-limit">Maximales Berechnungsbudget: 20 Sekunden</div></div>';if(!state.result)return '<div class="empty">Wähle genau vier eigene Spieler und starte die Berechnung. Die Auswahl einer Mannschaft oder eines Gegners startet noch keine Analyse.</div>';if(!state.result.recommendation)return `<div class="empty"><strong>Berechnung nicht abgeschlossen.</strong><br>${state.result.message||state.result.error||'Unbekannter Fehler'}</div>`;const b=state.result.recommendation;return `<p class="muted">${state.selectedOpp.length===4?'Die tatsächlichen vier Gegner sind bekannt; ihre Positionen werden intern berücksichtigt.':'Die wahrscheinlichen gegnerischen Vierergruppen werden intern gewichtet.'}</p><div class="optimal-result"><div class="optimal-label">Empfohlene Aufstellung</div><div class="optimal-players">${b.players.map((n,i)=>`<div class="optimal-player"><span>${i+1}</span><strong>${n}</strong></div>`).join('')}</div><div class="win-probability">${pct(b.team_win_probability)} <span>Mannschafts-Siegwahrscheinlichkeit</span></div></div><h3>Alternativen</h3><ol class="prediction-list">${state.result.recommendations.slice(1,5).map(x=>`<li><span>${x.players.join(' · ')}</span><strong>${pct(x.team_win_probability)}</strong></li>`).join('')}</ol>`;}
function pct(v){return `${(Number(v)*100).toFixed(1).replace('.',',')} %`;}
function bind(){app.querySelectorAll('select').forEach(el=>el.addEventListener('change',async e=>{const field=e.target.dataset.field;state[field]=e.target.value;state.result=null;await loadTeamPlayers();render();}));app.querySelectorAll('[data-player]').forEach(el=>el.addEventListener('click',e=>{const group=e.currentTarget.dataset.group,key=group==='own'?'selectedOwn':'selectedOpp',id=e.currentTarget.dataset.player;state[key]=state[key].includes(id)?state[key].filter(x=>x!==id):state[key].length<4?[...state[key],id]:state[key];state.result=null;render();}));app.querySelector('[data-action="analyze"]')?.addEventListener('click',runAnalysis);}
async function runAnalysis(){if(state.selectedOwn.length!==4||new Set(state.selectedOwn).size!==4||state.analysisLoading)return;state.analysisLoading=true;state.result=null;render();const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),21000);try{const actual=state.selectedOpp.length===4?'&actual_opponent_ids='+encodeURIComponent(state.selectedOpp.join(',')):'';state.result=await apiWithSignal(`/api/analysis?own_player_ids=${encodeURIComponent(state.selectedOwn.join(','))}&opponent_team=${encodeURIComponent(state.opponentTeam)}${actual}`,controller.signal);}catch(e){state.result={recommendations:[],message:e.name==='AbortError'?'Die Berechnung dauert länger als erwartet (20 Sekunden). Bitte erneut versuchen.':e.message};}finally{clearTimeout(timeout);state.analysisLoading=false;render();}}
async function apiWithSignal(path,signal){const r=await fetch(path,{signal});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.message||d.error||'API error');return d;}
init();
